import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { EnquiryForm } from "@/components/EnquiryForm";
import { categories, company, industries, pageContent, products } from "@/lib/site-data";

export async function generateMetadata({ params }: { params: Promise<{ slug?: string[] }> }): Promise<Metadata> {
  const path = (await params).slug?.join("/") || "";
  const product = path.startsWith("products/") ? products.find(p => p.slug === path.split("/")[1]) : undefined;
  const title = product?.name || pageContent[path]?.title || (path === "products" ? "Industrial Fastener Products" : path === "contact" ? "Contact" : path === "quote" ? "Request a Quote" : "Sriyaan Metals");
  return { title, description: product ? `${product.name}: ${product.standard}, ${product.grade}, ${product.sizes}. Enquire with Sriyaan Metals.` : pageContent[path]?.intro || "Contact Sriyaan Metals for industrial fastener requirements.", alternates: { canonical: `/${path}` } };
}

function Hero({ eyebrow, title, intro }: { eyebrow: string; title: string; intro: string }) {
  return <section className="technical-grid border-b border-white/10 bg-carbon pt-36"><div className="container-site py-20"><p className="eyebrow">{eyebrow}</p><h1 className="display mt-6 max-w-5xl text-5xl uppercase md:text-7xl lg:text-8xl">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-fog/75">{intro}</p></div></section>;
}

export default async function ContentPage({ params, searchParams }: { params: Promise<{ slug?: string[] }>; searchParams: Promise<{ category?: string }> }) {
  const parts = (await params).slug || [];
  const path = parts.join("/");
  if (path === "products") {
    const selected = (await searchParams).category;
    const list = selected ? products.filter(p => p.category === selected) : products;
    return <><Hero eyebrow="Technical catalogue" title="Industrial fasteners" intro="Browse representative products by standard, grade, material, size and application. Contact us for exact availability and pricing."/><section className="bg-paper py-20 text-ink"><div className="container-site"><div className="flex flex-wrap gap-2">{[undefined,...categories.map(c=>c.slug)].map(x=><Link key={x||"all"} href={x?`/products?category=${x}`:"/products"} className={`border px-4 py-2 text-xs font-bold uppercase tracking-wider ${selected===x||(!selected&&!x)?"border-teal-dark bg-teal-dark text-white":"border-ink/15"}`}>{x?categories.find(c=>c.slug===x)?.name:"All products"}</Link>)}</div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{list.map(p=><Link key={p.slug} href={`/products/${p.slug}`} className="group border border-ink/10 bg-white p-7"><p className="text-[.65rem] font-bold uppercase tracking-wider text-teal-dark">{p.standard}</p><h2 className="mt-5 font-display text-2xl font-bold uppercase">{p.name}</h2><p className="mt-4 text-sm text-slate-600">{p.material} · {p.grade}</p><span className="mt-8 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-orange-dark">View specifications <ArrowRight size={15}/></span></Link>)}</div></div></section></>;
  }
  if (parts[0] === "products" && parts[1]) {
    const p = products.find(x=>x.slug===parts[1]); if (!p) return <Hero eyebrow="Catalogue" title="Product not found" intro="Return to the product catalogue to continue browsing."/>;
    const specs = [["Standard",p.standard],["Material",p.material],["Grade",p.grade],["Size range",p.sizes],["Finish",p.finish],["Applications",p.applications]];
    return <><Hero eyebrow={categories.find(c=>c.slug===p.category)?.name||"Product"} title={p.name} intro="Representative technical details. Final supply is confirmed against the complete enquiry specification."/><section className="bg-paper py-20 text-ink"><div className="container-site grid gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><div className="relative aspect-[16/11] overflow-hidden bg-ink"><Image src="/images/product-range.jpg" alt={p.name} fill sizes="(max-width:1024px) 100vw,55vw" className="object-cover"/></div><div className="mt-8 grid gap-px bg-ink/10 sm:grid-cols-2">{specs.map(([k,v])=><div key={k} className="bg-white p-5"><dt className="text-[.65rem] font-bold uppercase tracking-wider text-slate-500">{k}</dt><dd className="mt-2 font-semibold">{v}</dd></div>)}</div></div><aside className="bg-white p-7 lg:p-9"><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-dark">Enquire for this product</p><h2 className="mt-4 font-display text-3xl font-bold uppercase">Share quantity and delivery requirement</h2><div className="mt-7"><EnquiryForm type="quote" product={p.name}/></div><a className="mt-5 flex items-center justify-center gap-2 border border-[#25D366] px-4 py-3 text-xs font-bold uppercase tracking-wider text-[#128c46]" href={`https://wa.me/${company.whatsapp}?text=${encodeURIComponent(`Hello Sriyaan Metals, I need a quote for ${p.name} (${p.standard}).`)}`} target="_blank" rel="noreferrer"><MessageCircle size={16}/> Ask on WhatsApp</a></aside></div></section></>;
  }
  if (["contact","quote","vendor"].includes(path)) {
    const isQuote=path==="quote", isVendor=path==="vendor";
    return <><Hero eyebrow={isVendor?"Supplier network":isQuote?"Request for quotation":"Talk to our team"} title={isVendor?"Become a Sriyaan Metals vendor":isQuote?"Tell us what you need":"Contact Sriyaan Metals"} intro={isVendor?"Introduce your products, capacity and certifications for supplier evaluation.":"Send a standard, drawing, bill of materials or general requirement. We will respond during business hours."}/><section className="bg-paper py-20 text-ink"><div className="container-site grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><h2 className="font-display text-2xl font-bold uppercase">Business desk</h2><ul className="mt-7 space-y-6 text-sm leading-7 text-slate-600"><li className="flex gap-3"><Phone className="mt-1 text-orange-dark" size={18}/><span>{company.phones.join(" / ")}</span></li><li className="flex gap-3"><Mail className="mt-1 text-orange-dark" size={18}/><span>{company.email}<br/>{company.emails.sales}</span></li><li className="flex gap-3"><MapPin className="mt-1 shrink-0 text-orange-dark" size={18}/><span>{company.address}</span></li></ul><p className="mt-8 border-t border-ink/10 pt-6 text-xs font-bold uppercase tracking-wider text-teal-dark">{company.hours}</p></div><div className="border border-ink/10 bg-white p-6 md:p-10"><EnquiryForm type={isVendor?"vendor":isQuote?"quote":"contact"}/></div></div></section></>;
  }
  if (path === "privacy" || path === "terms") return <><Hero eyebrow="Legal" title={path==="privacy"?"Privacy policy":"Terms & conditions"} intro="Website policy information for Sriyaan Metals."/><section className="bg-paper py-20 text-ink"><div className="container-site max-w-3xl space-y-5 leading-8 text-slate-600"><p>This website collects information submitted through enquiry forms solely to respond to business requirements and manage commercial communication.</p><p>Final legal, privacy, cookie and retention wording must be reviewed and approved before production launch.</p></div></section></>;
  const content = pageContent[path] || pageContent.about;
  return <><Hero eyebrow={content.eyebrow} title={content.title} intro={content.intro}/><section className="bg-paper py-20 text-ink"><div className="container-site grid gap-12 lg:grid-cols-[1fr_.8fr]"><div className="space-y-6 text-lg leading-9 text-slate-600">{content.body.map(x=><p key={x}>{x}</p>)}{path==="industries"&&<div className="mt-10 grid gap-px bg-ink/10 sm:grid-cols-2">{industries.map(x=><div key={x} className="bg-white p-5 font-display font-semibold uppercase">{x}</div>)}</div>}</div><div className="relative min-h-80 overflow-hidden"><Image src={path==="quality"?"/images/inspection.jpg":path==="global-reach"||path==="import-export"?"/images/export.jpg":"/images/manufacturing.jpg"} alt="Sriyaan Metals industrial capability" fill sizes="(max-width:1024px) 100vw,40vw" className="object-cover"/></div></div></section><section className="bg-teal py-14 text-ink"><div className="container-site flex flex-col justify-between gap-6 md:flex-row md:items-center"><h2 className="font-display text-3xl font-bold uppercase">Have a specification or drawing?</h2><Link className="btn bg-ink text-white" href="/quote">Request a quote <ArrowRight size={16}/></Link></div></section></>;
}
