import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle2, ClipboardCheck, Globe2, PackageCheck, ShieldCheck, Truck } from "lucide-react";
import { Reveal } from "@/components/Reveal";
import { categories, company, industries, products, standards } from "@/lib/site-data";

export default function Home() {
  return <>
    <section className="technical-grid relative min-h-[100svh] overflow-hidden bg-ink">
      <Image src="/images/hero-fasteners.jpg" alt="Precision industrial fasteners" fill priority sizes="100vw" className="object-cover object-center" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,#071117_4%,rgba(7,17,23,.92)_38%,rgba(7,17,23,.32)_72%,rgba(7,17,23,.68))]" />
      <div className="absolute inset-x-0 bottom-0 h-52 bg-gradient-to-t from-ink to-transparent" />
      <div className="container-site relative z-10 flex min-h-[100svh] items-end pb-20 pt-32 lg:pb-24">
        <div className="max-w-4xl">
          <p className="eyebrow">Industrial fasteners · Mumbai, India</p>
          <h1 className="display mt-6 text-[clamp(4rem,9vw,8.2rem)] uppercase">Strength in<br/><span className="text-teal">every joint.</span></h1>
          <p className="mt-7 max-w-2xl text-base leading-8 text-fog/85 sm:text-lg">Standard and special fasteners sourced, inspected and supplied for construction, engineering, automotive and infrastructure requirements.</p>
          <div className="mt-9 flex flex-wrap gap-3"><Link href="/quote" className="btn btn-primary">Request a quote <ArrowRight size={16}/></Link><Link href="/products" className="btn btn-secondary">Explore products</Link></div>
          <div className="mt-12 flex flex-wrap gap-x-8 gap-y-3 border-t border-white/12 pt-6">{standards.map(s => <span key={s} className="font-display text-sm font-bold tracking-[.18em] text-fog/65">{s}</span>)}</div>
        </div>
      </div>
      <div className="absolute bottom-0 right-0 hidden border-l border-t border-white/12 bg-ink/70 px-8 py-5 backdrop-blur lg:block"><p className="text-[.65rem] uppercase tracking-[.2em] text-muted">Direct enquiry</p><a className="mt-1 block font-display text-xl font-semibold" href={`tel:${company.phones[0].replace(/\s/g,"")}`}>{company.phones[0]}</a></div>
    </section>

    <section className="bg-paper py-24 text-ink">
      <div className="container-site"><Reveal><p className="eyebrow !text-teal-dark">Product catalogue</p><div className="mt-5 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="display max-w-3xl text-5xl uppercase md:text-7xl">Fasteners for every critical connection</h2><Link href="/products" className="text-xs font-bold uppercase tracking-[.16em] text-teal-dark">View complete range →</Link></div></Reveal>
      <div className="mt-14 grid gap-px bg-ink/10 sm:grid-cols-2 lg:grid-cols-4">{categories.map((c,i)=><Reveal key={c.slug} delay={i*.04} className="bg-paper"><Link href={`/products?category=${c.slug}`} className="group block min-h-64 p-7 transition-colors hover:bg-white"><span className="font-display text-sm font-bold text-teal-dark">{c.code}</span><h3 className="mt-12 font-display text-2xl font-bold uppercase tracking-tight">{c.name}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{c.description}</p><ArrowRight className="mt-6 text-orange transition-transform group-hover:translate-x-2" size={18}/></Link></Reveal>)}</div></div>
    </section>

    <section className="relative overflow-hidden bg-carbon py-24"><div className="container-site grid gap-12 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><Reveal><p className="eyebrow">Why Sriyaan</p><h2 className="display mt-5 text-5xl uppercase md:text-7xl">Supply engineered around your specification</h2><p className="mt-7 max-w-xl leading-8 text-fog/75">We connect product knowledge, disciplined sourcing, inspection support and responsive communication so procurement teams can move with confidence.</p><Link href="/about" className="btn btn-secondary mt-9">About Sriyaan Metals</Link></Reveal><div className="grid gap-3 sm:grid-cols-2">{[[ShieldCheck,"Specification first","Standards, material, grade, dimensions and finish reviewed before supply."],[ClipboardCheck,"Quality support","Inspection and documentation aligned with order requirements."],[PackageCheck,"Catalogue + specials","Standard products and drawing-based requirements through one desk."],[Truck,"Export coordination","Commercial documents, packing and shipment planning support."]].map(([Icon,t,d],i)=>{const C=Icon as typeof ShieldCheck;return <Reveal key={String(t)} delay={i*.06}><article className="card-line min-h-56 p-7"><C className="text-teal" strokeWidth={1.4}/><h3 className="mt-8 font-display text-xl font-bold uppercase">{String(t)}</h3><p className="mt-3 text-sm leading-6 text-muted">{String(d)}</p></article></Reveal>})}</div></div></section>

    <section className="bg-paper py-24 text-ink"><div className="container-site grid gap-12 lg:grid-cols-2 lg:items-center"><Reveal className="relative aspect-[16/11] overflow-hidden"><Image src="/images/inspection.jpg" alt="Fastener quality inspection" fill sizes="(max-width:1024px) 100vw,50vw" className="object-cover"/><div className="absolute bottom-0 left-0 bg-ink px-6 py-5 text-paper"><p className="text-[.65rem] uppercase tracking-[.2em] text-teal">Quality focus</p><p className="mt-1 font-display text-lg font-bold uppercase">Verify. Document. Deliver.</p></div></Reveal><Reveal><p className="eyebrow !text-teal-dark">Quality & documentation</p><h2 className="display mt-5 text-5xl uppercase md:text-7xl">Confidence you can measure</h2><p className="mt-7 leading-8 text-slate-600">Quality requirements are established before order placement and carried through product identification, dimensional checks, traceability and agreed documentation.</p><ul className="mt-8 grid gap-4">{["Material and grade verification","Dimensional inspection support","Coating and finish documentation","Third-party inspection coordination"].map(x=><li key={x} className="flex items-center gap-3 text-sm font-semibold"><CheckCircle2 className="text-teal-dark" size={19}/>{x}</li>)}</ul><Link href="/quality" className="btn btn-primary mt-9">Quality approach</Link></Reveal></div></section>

    <section className="relative min-h-[720px] overflow-hidden"><Image src="/images/manufacturing.jpg" alt="Industrial manufacturing capability" fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-ink via-ink/85 to-ink/25"/><div className="container-site relative z-10 flex min-h-[720px] items-center py-24"><Reveal className="max-w-2xl"><p className="eyebrow">Infrastructure & network</p><h2 className="display mt-5 text-5xl uppercase md:text-7xl">A capable route from drawing to dispatch</h2><p className="mt-7 leading-8 text-fog/80">The supply route is selected around product complexity, volume, lead time and documentation—covering sourcing, manufacturing support, inspection, packing and delivery coordination.</p><div className="mt-9 flex gap-3"><Link href="/infrastructure" className="btn btn-primary">Explore capability</Link><Link href="/vendor" className="btn btn-secondary">Become a vendor</Link></div></Reveal></div></section>

    <section className="bg-ink py-24"><div className="container-site"><Reveal><p className="eyebrow">Industries served</p><h2 className="display mt-5 text-5xl uppercase md:text-7xl">Built into the systems that move industry</h2></Reveal><div className="mt-14 grid gap-px bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{industries.map((x,i)=><Reveal key={x} delay={i*.04} className="bg-ink"><div className="flex min-h-36 items-end justify-between p-6"><span className="font-display text-xl font-semibold uppercase">{x}</span><span className="text-xs text-teal">0{i+1}</span></div></Reveal>)}</div></div></section>

    <section className="bg-paper py-24 text-ink"><div className="container-site"><Reveal><div className="grid gap-8 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="eyebrow !text-teal-dark">Featured products</p><h2 className="display mt-5 text-5xl uppercase md:text-7xl">Specification-ready range</h2></div><p className="leading-7 text-slate-600">Browse representative products by standard, material, grade, size and finish. Share your exact requirement for availability and commercial terms.</p></div></Reveal><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{products.map((p,i)=><Reveal key={p.slug} delay={i*.04}><Link href={`/products/${p.slug}`} className="group block border border-ink/10 bg-white p-7 transition-transform hover:-translate-y-1"><span className="text-[.65rem] font-bold uppercase tracking-[.16em] text-teal-dark">{p.standard}</span><h3 className="mt-5 font-display text-2xl font-bold uppercase">{p.name}</h3><dl className="mt-7 grid grid-cols-2 gap-4 border-t border-ink/10 pt-5 text-xs"><div><dt className="text-slate-500">Grade</dt><dd className="mt-1 font-semibold">{p.grade}</dd></div><div><dt className="text-slate-500">Sizes</dt><dd className="mt-1 font-semibold">{p.sizes}</dd></div></dl><span className="mt-7 flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-orange-dark">View product <ArrowRight size={15} className="transition-transform group-hover:translate-x-1"/></span></Link></Reveal>)}</div></div></section>

    <section className="relative overflow-hidden bg-carbon py-24"><div className="container-site grid gap-12 lg:grid-cols-2 lg:items-center"><Reveal><p className="eyebrow">Global business</p><h2 className="display mt-5 text-5xl uppercase md:text-7xl">Mumbai connected to international industry</h2><p className="mt-7 max-w-xl leading-8 text-fog/75">Responsive export communication, documentation coordination, inspection support and fit-for-purpose packing for international requirements.</p><Link href="/global-reach" className="btn btn-secondary mt-9"><Globe2 size={16}/> Global reach</Link></Reveal><Reveal className="relative aspect-[16/11] overflow-hidden border border-white/12"><Image src="/images/export.jpg" alt="Industrial export packing and logistics" fill sizes="(max-width:1024px) 100vw,50vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-ink/80 to-transparent"/><div className="absolute bottom-6 left-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-teal">Export support</p><p className="mt-2 font-display text-2xl font-bold uppercase">Documents · Inspection · Packing · Logistics</p></div></Reveal></div></section>

    <section className="bg-teal py-20 text-ink"><div className="container-site flex flex-col justify-between gap-8 lg:flex-row lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.22em]">Start a requirement</p><h2 className="display mt-4 max-w-4xl text-5xl uppercase md:text-7xl">Send the standard. Grade. Size. Quantity. We’ll take it from there.</h2></div><Link href="/quote" className="btn shrink-0 bg-ink !px-7 text-paper">Request quotation <ArrowRight size={17}/></Link></div></section>
  </>;
}
